#!/bin/sh
diff=no
pager=cat
backup=no
if command -v less >/dev/null; then
	pager=less
fi
if command -v bat >/dev/null; then
	pager='bat -ldiff'
fi
if command -v delta >/dev/null; then
	pager='delta -'
fi
while getopts 'db' opt; do
	case "$opt" in
		d)
			diff=yes
			;;
		b)
			backup=yes
			;;
	esac
done

shift $((OPTIND - 1))

if [ $diff == yes ]; then
	while read filename; do
		eval "$@ '$filename' | diff -u $filename -"
	done | $pager
else
	date="$(date -I)"
	while read filename; do
		cp -v -- "$filename" "$filename.backup-$date" && < "$filename" $@ | sponge "$filename"
	done
fi
