#!/bin/sh
dirA="$1"
dirB="$2"
if ! [ -d "$dirA" -a -d "$dirB" ]; then
	echo 'Usage: bettervimdiff DIR1 DIR2' >&2
	exit 1
fi
tmpfile="$(mktemp)"
find "$dirA" "$dirB" -type f -printf '%P\n' |
	awk '!a[$0] {print $0; a[$0]=1}' |
	awk -vA="$dirA" -vB="$dirB" '
	BEGIN {
		first=1
		escapeA=A
		escapeB=B
		gsub(/([^[:alnum:]\/])/, "\\\\&", escapeA)
		gsub(/([^[:alnum:]\/])/, "\\\\&", escapeB)
	}
	{
		escapeFile=$0
		gsub(/([^[:alnum:]\/])/, "\\\\&", escapeFile)
	}
	!first {
		print ":tabnew"
	}
	{
		fileA=A"/"$0
		fileB=B"/"$0
		if((getline _ < fileB) != -1)
			print ":view "escapeB"/"escapeFile
		else
			print ":view /dev/null"
		print ":vsplit"
		if((getline _ < fileA) != -1)
			print ":view "escapeA"/"escapeFile
		else
			print ":view /dev/null"
		print ":windo diffthis"
	}
	first {
		first=0
	}

' >"$tmpfile"
exec 3<"$tmpfile"
/usr/bin/vim --noplugins -s '/dev/fd/3'
#cat "$tmpfile"
rm "$tmpfile"
