#!/bin/sh

if ! [ -f "/etc/co" ]; then
	echo 'File /etc/co with completions not found' >&2
	sleep 2
	exit 1
fi
args="$@"
tmp="$(mktemp)"
tmux popup -E "fzf $FZF_DEFAULT_OPTS -1 -q \"$args\" > \"$tmp\" </etc/co"
cat "$tmp"
rm "$tmp"
