#!/bin/bash
while [ "$PWD" != / -a ! -f build.gradle ]; do
	cd "$(dirname "$PWD")"
done

if ! [ -f build.gradle ]; then
	exit 1
fi

remote=gradle@direct.filipsjanis.com
remotehome=/home/gradle/projects

remotedir="$remotehome/${PWD////_}"

rsync -ircu --exclude build --exclude .gradle --exclude '**.swp' --delete . "$remote:$remotedir"
# https://stackoverflow.com/questions/6592376/prevent-ssh-from-breaking-up-shell-script-parameters
ssh -t "$remote" gradle -p "$remotedir" "${@@Q}" "; mkdir -p $remotedir/build"
rsync --delete -ircuq "$remote:$remotedir/build" . | (grep -v '/$' || true)
