#!/bin/sh
while [ "$PWD" != / -a ! -f build.gradle ]; do
	cd "$(dirname "$PWD")"
done

if ! [ -f build.gradle ]; then
	exit 1
fi

remote=gradle@direct.filipsjanis.com
remotehome=/home/gradle/projects

remotedir="$remotehome/${PWD////_}"

rsync -ircu --exclude build --exclude .gradle --exclude '**.swp' --delete . "$remote:$remotedir"
ssh -t "$remote" gradle -p "$remotedir" "$@" "; mkdir -p $remotedir/build"
rsync --delete -ircu "$remote:$remotedir/build" . | (grep -v '/$' || true)
