#!/bin/bash

m4_changequote({{,}})
m4_changecom({{###}})

[ -z "$PS1" ] && return

if [ -z "$TMUX$VIM_TERMINAL" ] && command -v tmux > /dev/null &&
			groups "$USER" | tr ' ' '\n' | grep -q '^tmuxers$' &&
			[ -z "$(tmux list-clients)" ]; then
	SHLVL=0 tmux new -A -c ~
fi

# prompt
promptcolor=${promptcolor:-$((RANDOM % 213 + 17))}
PS0='\[\e[0m\]'

_on_command_error() {
	exitcode="$?"
	printf "\x1b[97;41m[= %d]\x1b[0m\n" "$exitcode"
	stty sane
}
trap '_on_command_error' ERR

if [ -n "$TMUX" ]; then
	# dont put directory when in tmux
	PS1='\[\e[1;38;5;${promptcolor}m\]${SSH_CLIENT/?*/R}${SHLVL/#1}ᛋ \[\e[97;1m\]'
else
	PS1='\[\e[1;38;5;${promptcolor}m\]\u ${SSH_CLIENT/?*/R}${SHLVL/#1}[\[\e[0m\]\w\[\e[1;38;5;${promptcolor}m\]]ᛋ \[\e[97;1m\]'
fi

stty ixon ixoff ek ixany # 'ek' fixes ctrl+backspace

if command -v fzf >/dev/null; then
	hist() {
		# sort & uniq by second field; then "unsort" using first field
		cmd="$(history | sort -u -k2 | sort -n |
			sed -n 's/^\s*[0-9]*\s*//; /...../p' |
			fzf --tac --reverse --height='80%')"
		printf '%s\n' "$cmd"
	}
	bind -x '"\C-r": "history -s $(hist)"'
fi

# Ctrl-Down
bind -x '"\e[1;5B": "cd .."'
bind    '"\C-g\C-k": "git commit -m \"\"\e[D"'
bind    '"\C-f": " | grep '\'\''\e[D"'
bind -x '"\ec": "history -s $READLINE_LINE"'
bind    '"\\": "|"'

# list files upon completing empty line
complete -Ef

shopt -s histreedit histverify histappend autocd dirspell cdspell globstar checkwinsize huponexit
printf 'm4_esyscmd(tabs 4 </dev/ptmx >&0 2>&0)'

HISTSIZE=2000
HISTCONTROL=ignoredups:ignorespace:erasedups

m4_include(less_termcap)

# disable the "command not found" event if it's slow
unset command_not_found_handle

m4_include(portable_aliases)

if [ -f /usr/local/etc/bashrc ]; then
	. /usr/local/etc/bashrc
fi

if [ -f ~/.bashrc_local ]; then
	. ~/.bashrc_local
fi
