#!/bin/bash

m4_changequote({{,}})
m4_changecom({{###}})

# =========================================
# this part is executed regardless of whether the shell is interactive
# =========================================

m4_syscmd(command -v colorspec >/dev/null)
m4_ifelse(0,m4_sysval,{{
export GREP_COLORS="m4_esyscmd(colorspec -Fgrep grepcolors)"
export LS_COLORS="m4_esyscmd(colorspec -Fls lscolors)"
export GCC_COLORS="m4_esyscmd(colorspec -Fgcc gcccolors)"
}})
if [ -f ~/.path ]; then
	export PATH="$(cat ~/.path | grep '^/' | tr '\n' ':' | sed -E 's/::+/:/g; s/:$//')"
else
	export PATH='/usr/local/bin:/usr/bin:bin'
fi
export GTAGSLABEL=ctags
export LANG='en_US.utf8'
export IGNOREEOF='0'
export FIGNORE='..:.'
export GRADLE_OPTS=''
less_prompt='file\ %g\ (%i\ of\ %m)\ line\ %lt╱%L\ =\ %Pt\%'
export LESS='--jump-target=2 --tabs=3 --RAW-CONTROL-CHARS --QUIET --ignore-case --clear-screen -P'"$less_prompt"
export MANOPT='--nh -r '"${less_prompt/\%g/\$MAN_PN}"
export GPG_TTY="$(tty)"
export PAGER="$(command -v less)"
export DELTA_PAGER="$PAGER --" # seems like adding any option (like --) prevents delta from adding its own options
export EDITOR="$(command -v nano)"
export VISUAL="$EDITOR"
export LESSGLOBALTAGS=global
command -v lesspipe.sh >/dev/null && export LESSOPEN='||lesspipe.sh %s'
# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
# set tab size to 4
tabs 4
umask 022
# allow core dumps
ulimit -c unlimited

# =========================================
# If not running interactively, return here
# =========================================
[ -z "$PS1" ] && return

m4_include(promptfunc)

$PROMPT_COMMAND


if [ -z "$TMUX" ] && [ -z "$SSH_CLIENT" ] && command -v tmux > /dev/null; then
#	if ! timeout -s KILL 1s tmux run-shell true; then
#		pkill -9 'tmux: server'
#		pkill -9 'tmux: client'
#		echo 'Forcefully killed tmux' >&2
#		sleep 1
#	fi
	SHLVL=0 tmux new -A -c ~
fi

stty ixon
stty ixoff
stty ek # fix ctrl+backspace
stty ixany

# Ctrl-Down
bind -x '"\e[1;5B": "cd ..; $PROMPT_COMMAND"'
bind    '"\C-k": "git commit -m \"\"\e[D"'
bind    '"\C-f": "!! | grep '\'\''\e[D"'
bind -x '"\ec": "history -s $READLINE_LINE"'
bind    '"\\": "|"'

# list files upon completing empty line
complete -Ef
complete -F _git g
complete -F _make mk
complete -F _pacman pm

shopt -s histreedit
shopt -s histverify
shopt -s histappend
shopt -s autocd
shopt -s dirspell
shopt -s cdspell
shopt -s globstar
# lesson learnt - nullglob is a bad idea because it breaks variable expansion
shopt -u extdebug

#trap 'kill $(jobs -p) 2>/dev/null' EXIT

HISTCONTROL=ignoredups:ignorespace:erasedups
#unset HISTFILE
# append to the history file, don't overwrite it
# shopt -s histappend

# make less more friendly for non-text input files, see lesspipe(1)
command -v lesspipe >/dev/null && eval "$(SHELL=/bin/sh lesspipe)"

m4_include(less_termcap)

# disable the "command not found" event if it's slow
unset command_not_found_handle

m4_include(portable_aliases)

if [ -f /usr/local/etc/bashrc ]; then
	. /usr/local/etc/bashrc
fi

if [ -f ~/.bashrc_local ]; then
	. ~/.bashrc_local
fi
