#!/bin/bash

m4_changequote({{,}})
m4_changecom({{###}})

[ -z "$PS1" ] && return

m4_include(promptfunc)

if [ -z "$TMUX" ] && [ -z "$SSH_CLIENT" ] && command -v tmux > /dev/null; then
	if timeout -s KILL 1s tmux run-shell true; then
		SHLVL=0 tmux new -A -c ~
		return
	fi
fi

stty ixon
stty ixoff
stty ek # fix ctrl+backspace
stty ixany

# Ctrl-Down
bind -x '"\e[1;5B": "cd ..; $PROMPT_COMMAND"'
bind    '"\C-g\C-k": "git commit -m \"\"\e[D"'
bind    '"\C-f": "!! | grep '\'\''\e[D"'
bind -x '"\ec": "history -s $READLINE_LINE"'
bind    '"\\": "|"'

# list files upon completing empty line
complete -Ef

shopt -s histreedit
shopt -s histverify
shopt -s histappend
shopt -s autocd
shopt -s dirspell
shopt -s cdspell
shopt -s globstar
# lesson learnt - nullglob is a bad idea because it breaks variable expansion
shopt -u extdebug

#trap 'kill $(jobs -p) 2>/dev/null' EXIT

HISTSIZE=2000
HISTCONTROL=ignoredups:ignorespace:erasedups
#unset HISTFILE
# append to the history file, don't overwrite it
# shopt -s histappend

m4_include(less_termcap)

# disable the "command not found" event if it's slow
unset command_not_found_handle

m4_include(portable_aliases)

if [ -f /usr/local/etc/bashrc ]; then
	. /usr/local/etc/bashrc
fi

if [ -f ~/.bashrc_local ]; then
	. ~/.bashrc_local
fi

if [ -f /usr/share/bash-complete-alias/complete_alias ]; then
	source /usr/share/bash-complete-alias/complete_alias
	for a in $(alias|cut -d= -f1|cut -d' ' -f2); do
		complete -F _complete_alias "$a"
	done
fi
