#!/bin/sh
# A script which contains the function definition for prompt function

if [ -e /etc/profile.d/promptcolor.sh ]; then
	. /etc/profile.d/promptcolor.sh
else
	promptcolor=${promptcolor:15}
	promptcolor2=${promptcolor2:15}
fi


_on_command_start() {
	printf "\x1b[0m" >/dev/tty
}
trap '_on_command_start' DEBUG
_on_command_error() {
	exitcode="$?"
	printf "\x1b[97;41m[= %d]\x1b[0m\n" "$exitcode"
	stty sane
}
trap '_on_command_error' ERR

_promptfunc() {
	PS1="\[\e[38;5;${promptcolor}m\]${SSH_CLIENT/?*/R}${SHLVL/#1}ᛋ \[\e[97;1m\]"
}
if echo "$TERM" | grep -q 256; then
	PROMPT_COMMAND=_promptfunc
fi
