#!/bin/sh

if [ "$(id)" -ne '0' ]; then
	echo "Must run as root"
	exit 1
fi

if [ -e /gnu ]; then
	echo "/gnu already exists, nothing done"
	exit 1
fi

binname='guix-binary-1.3.0.x86_64-linux.tar.xz'

set -e
set -m
set -x

cd /root/
wget "https://ftp.gnu.org/gnu/guix/$binname"
cd /tmp/
tar -xf "/root/$binname"
mv ./var/guix/ /var/
mv ./gnu /
cd /root/
mkdir -p .config/guix/
mkdir -p /usr/local/bin/
ln -s /var/guix/profiles/per-user/root/current-guix/bin/guix /usr/local/bin/
ln -s /var/guix/profiles/per-user/root/current-guix/bin/guix-daemon /usr/local/bin/
cp /root/.config/guix/current/etc/openrc/guix-daemon /etc/init.d
chmod 775 /etc/init.d/guix-daemon
echo 'Guix has been installed successfully, now will try to add users and groups and launch daemon. These steps are not critical and can be run at a later time'
mkdir -p /var/empty2/
chmod "$(stat -c %a /var/empty)" /var/empty2
addgroup -S guixbuild
for i in $(seq -w 1 8); do
	adduser -G guixbuild -h /var/empty2 -s /sbin/nologin -g "Guix build user $i" -S "guixbuilder$i";
done
rc-update add guix-daemon default
rc-service guix-daemon start
guix archive --authorize < '/root/.config/guix/current/share/guix/ci.guix.gnu.org.pub'
guix install hello
guix gc
set +x
echo 'Add the follwing lines to your shell profile:'
cat <<'EOM'
	if [ -d "$HOME/.guix-profile" ]; then
		export GUIX_PROFILE="$HOME/.guix-profile"
		. "$GUIX_PROFILE/etc/profile"
	fi
EOM
